apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: levelup-frontend-servicemonitor
  namespace: levelup-frontend
  labels:
    app.kubernetes.io/name: levelup-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: levelup-frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

