apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "thongnv701@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # HTTP-01 solver for nginx ingress (default for all domains)
    - http01:
        ingress:
          class: nginx