apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  # We're not including aws-secret.yaml or aws-credentials.yaml 
  # because they contain sensitive information that is managed 
  # directly by the GitHub workflow through Kubernetes secrets 