apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-servicemonitor
  namespace: portfolio
  labels:
    app: portfolio-app
spec:
  selector:
    matchLabels:
      app: portfolio-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s