apiVersion: v1
kind: ConfigMap
metadata:
  name: levelupaccounts-config
  namespace: levelupaccounts
data:
  ASPNETCORE_CONFIGURATION_PATH: "/app/config/appsettings.json"
  ENVIRONMENT_NAME: "prod"
  ASPNETCORE_ENVIRONMENT: "Staging"
