apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: levelupaccounts-servicemonitor
  namespace: levelupaccounts
  labels:
    app.kubernetes.io/name: levelupaccounts-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: levelupaccounts-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s