apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: levelupaccounts-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/platform-gitops.git
    targetRevision: main
    path: k8s/levelupaccounts
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: levelupaccounts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: github-auth