apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 18.2.1
    helm:
      parameters:
        - name: architecture
          value: standalone
        - name: auth.enabled
          value: "true"
        - name: master.persistence.enabled
          value: "true"
        - name: master.persistence.size
          value: 8Gi
        - name: master.service.type
          value: ClusterIP
        - name: master.service.ports.redis
          value: "6379"
        - name: sentinel.enabled
          value: "false"
        - name: metrics.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true